import type { Metadata } from 'next';
import './globals.css';
import Navbar from '../components/nav/Navbar';
import ToasterProvider from '../providers/ToasterProvider';
import { StoreProvider } from '../providers/StoreProvider';
import AuthSessionSync from '@/providers/AuthSessionSync';
import { SessionProvider } from 'next-auth/react';
import SignalRProvider from '@/providers/SignalRProvider';
import { getCurrentUser } from '@/actions/authActions';

export const metadata: Metadata = {
  title: 'Carsties',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang='en'>
      <body>
        <SessionProvider>
          <StoreProvider>
            <AuthSessionSync />
            <ToasterProvider />
            <Navbar />
            <main className='container mx-auto px-5 pt-10'>
              <SignalRProvider user={user}>
                {children}
              </SignalRProvider>
            </main>
          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
