// 'use client';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '../components/nav/Navbar';
import ToasterProvider from '../providers/ToasterProvider';
import { StoreProvider } from '../providers/StoreProvider';

export const metadata: Metadata = {
  title: 'Carsties',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <StoreProvider>
          <ToasterProvider />
          <Navbar />
          <main className='container mx-auto px-5 pt-10'>{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
